#!/bin/sh

# This script is to compile library

DIRECTORY="$(dirname "$0")"
fn=$1

export DIRECTORY
export fn

# Compile libcaer

case "$fn" in
    "make")
        if [ ! -d "$PWD/libcaer/build" ]; then
            echo "[MESSAGE] Compiling libcaer"
            cd libcaer
            mkdir build
            cmake -DCMAKE_INSTALL_PREFIX=./build .
            make
            make install
            cd ..
        else
            echo "[MESSAGE] libcaer compiled"
        fi

        if [ ! -d "$PWD/build" ]; then
            echo "[MESSAGE] Compiling pycaer"
            # Compile pycaer
            export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$PWD/libcaer/build/lib/pkgconfig
            mkdir build
            cd build
            cmake -DPYTHON_EXECUTABLE:FILEPATH=$(which python) ..
            make
        else
            echo "[MESSAGE] pycaer compiled"
        fi
    ;;

    "make.lib")
        echo "[MESSAGE] Compiling libcaer"
        cd libcaer
        if [ ! -d "$PWD/libcaer/build" ]; then
            mkdir build
        fi
        cmake -DCMAKE_INSTALL_PREFIX=./build .
        make
        make install
        cd ..
    ;;

    "make.py")
        echo "[MESSAGE] Compiling pycaer"
        # Compile pycaer
        export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$PWD/libcaer/build/lib/pkgconfig
        if [ ! -d "$PWD/build" ]; then
            mkdir build
        fi
        cd build
        cmake -DPYTHON_EXECUTABLE:FILEPATH=$(which python) ..
        make
    ;;

    "clean")
        # remove build directory
        echo "[MESSAGE] Removing pycaer build directory"
        rm -rf $PWD/build

        # remove libcaer files
        echo "[MESSAGE] Removing main compilation files"
        rm $PWD/libcaer/CMakeCache.txt
        rm -rf $PWD/libcaer/CMakeFiles
        rm $PWD/libcaer/Makefile
        rm -rf $PWD/libcaer/build
        rm $PWD/libcaer/cmake_install.cmake
        rm $PWD/libcaer/install_manifest.txt
        rm $PWD/libcaer/libcaer.pc

        echo "[MESSAGE] Removing documentation compilation files"
        rm $PWD/libcaer/docs/cmake_install.cmake
        rm -rf $PWD/libcaer/docs/CMakeFiles
        rm $PWD/libcaer/docs/libcaer_api.doxy
        rm $PWD/libcaer/docs/Makefile

        echo "[MESSAGE] Removing include compilation files"
        rm $PWD/libcaer/include/cmake_install.cmake
        rm -rf $PWD/libcaer/include/CMakeFiles
        rm $PWD/libcaer/include/libcaer.h
        rm $PWD/libcaer/include/Makefile

        echo "[MESSAGE] Removing includcpp compilation files"
        rm $PWD/libcaer/includecpp/cmake_install.cmake
        rm -rf $PWD/libcaer/includecpp/CMakeFiles
        rm $PWD/libcaer/includecpp/Makefile

        echo "[MESSAGE] Removing src compilation files"
        rm $PWD/libcaer/src/cmake_install.cmake
        rm -rf $PWD/libcaer/src/CMakeFiles
        rm $PWD/libcaer/src/Makefile
        echo "[MESSAGE] Removing compiled dynamic library"
        if [[ "$OSTYPE" == "linux-gnu" ]]; then
            # for linux
            rm $PWD/libcaer/src/*.so.*
        elif [[ "$OSTYPE" == "darwin"* ]]; then
            # for mac
            rm $PWD/libcaer/src/*.dylib
        fi
    ;;

esac
